[project]
name = "python-package"
version = "0.1.0"
description = ""
authors = [{ name = "Tom Solberg", email = "me@sbg.dev" }]
dependencies = []
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
