[package]
name = "axum-hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum = { version = "0.6.20", features = ["tokio"] }
tokio = { version = "1.0", features = ["full"] }
